steps:
  # Paso para construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/analytics:latest', 'backend/analytics/microservice/']

  - name: 'gcr.io/cloud-builders/docker'
    args:
        - push
        - 'gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/analytics:latest'
  # Despliegue en GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          PROJECT=$$(gcloud config get-value core/project)          
          gke-gcloud-auth-plugin --version
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials betaroma --zone us-central1-a --project handy-position-413808 
          kubectl delete -f kubernetes/dp-analytics.yaml
          kubectl apply -f kubernetes/dp-analytics.yaml