apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/analytics:latest
        ports:
        - containerPort: 8005