apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/shop:latest
        ports:
        - containerPort: 8002
