apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/user:latest
        ports:
        - containerPort: 8003
