apiVersion: apps/v1
kind: Deployment
metadata:
  name: xutilities
  labels:
    app: xutilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xutilities
  template:
    metadata:
      labels:
        app: xutilities
    spec:
      containers:
      - name: xutilities
        image: gcr.io/handy-position-413808/github.com/eingaruca/devops-ecommerce/xutilities:latest
        ports:
        - containerPort: 8004
