apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32702
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: user
  sessionAffinity: None
  type: NodePort