apiVersion: v1
kind: Service
metadata:
  labels:
    app: analytics
  name: analytics
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32705
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    app: analytics
  sessionAffinity: None
  type: NodePort