apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32700
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: NodePort