apiVersion: v1
kind: Service
metadata:
  labels:
    app: xutilitites
  name: xutilitites
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32704
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: xutilitites
  sessionAffinity: None
  type: NodePort