apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32701
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: product
  sessionAffinity: None
  type: NodePort